### PR TITLE
Mac drag and drop

### PR DESCRIPTION
**Pull request by Rockindash**
Drag and Drop to upload file option added for Mac, Issue #1046

### CODE REVIEW

**Comment by Rockindash** [comment]
SCREENSHOTS:

- File importer
Screenshot 2024-08-28 at 1 30 56 AM

- Text Fields
Screenshot 2024-08-28 at 1 30 38 AM

**Comment by johnnyluo** [comment]
Good work @Rockindash, Can you please investigate , is there a way we don't need to remove the sandbox?

**Comment by Rockindash** [comment]
We only need to remove it while running it via Xcode. The reason is Apple does not allow file access due to some security reasons while on a sandbox environment. For users it shouldn’t be a problem.
It seems like Apple doesn’t has this restriction while using file importer but for drag and drop they do.

**Review by johnnyluo — APPROVED** [review]
LGTM

**Pull request merged**
