### PR TITLE
validation for assets

### PR DESCRIPTION
**Pull request by enriquesouza**
Tests

Bond + all fields less asset -> OK

image

image

image

Unbond all fields less asset -> OK

image

image

image

image

### CODE REVIEW

**Comment by johnnyluo** [comment]
@enriquesouza 
CleanShot 2024-12-02 at 12 58 02@2x
This message is not good , because there is no "red asterisk" on "Asset"

**Comment by enriquesouza** [comment]
> @enriquesouza CleanShot 2024-12-02 at 12 58 02@2x This message is not good , because there is no "red asterisk" on "Asset"

I will add the mandatory *

**Comment by enriquesouza** [comment]
@johnnyluo the red start fix 

UNBOND
image
image

image


BOND

image

image

image

**Review by johnnyluo — APPROVED** [review]
LGTM

**Pull request merged**
